// ============================================================================
// CONTRACT: the zero-new-flags CLI path must stay byte-for-byte identical to
// released v0.5.0, forever. Every future PR is additive; any drift here on a
// no-flags invocation is a BREAKING CONTRACT CHANGE, not a fixture bug.
//
// If this test fails after a change you made:
//   - Do NOT "fix" it by regenerating the golden files to match new output.
//   - The failure means the report or snapshot shape changed for callers who
//     pass no new flags. That requires an explicit schemaVersion decision
//     (see lib/contract.mjs, REPORT_SCHEMA_VERSION) made deliberately by a
//     human, not silently absorbed by updating a fixture.
//   - If the change really is intentional and versioned correctly, regenerate
//     with GH_DELTA_UPDATE_BASELINE=1 (see below) and review the diff by hand
//     before committing it.
//
// Golden fixtures live in test/fixtures/baseline/. Each of the three
// invocations (run1: baseline seed, run2: tick with deltas, run3: no-change
// tick) has an `*-observation.json` (the shape fetchPRs/fetchIssues return)
// and expected `*-expected-report.json` / `*-expected-snapshot.json` files,
// generated by actually running lib/cli.mjs `run()` and hand-inspected before
// being committed (see scratchpad generator used at authoring time; the
// fixtures themselves are the durable artifact).
//
// To regenerate (only when a change is a deliberate, reviewed contract
// change): run this file with GH_DELTA_UPDATE_BASELINE=1 set, e.g.
//   GH_DELTA_UPDATE_BASELINE=1 node --test test/contract-baseline.test.mjs
// This rewrites the golden files from the current code's actual output
// instead of asserting against them. Review the diff before committing.
// ============================================================================
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, writeFileSync } from 'node:fs';

process.env.GH_DELTA_NO_REGISTRY = '1';

import { run } from '../lib/cli.mjs';
import { REPORT_FIELDS } from '../lib/contract.mjs';

const UPDATE = process.env.GH_DELTA_UPDATE_BASELINE === '1';

const FIX_DIR = new URL('./fixtures/baseline/', import.meta.url);
const REPO = 'acme/widgets';
const MONITOR_ID = 'contract-baseline';
const STATE_FILE = '/tmp/gh-delta-contract-baseline.json';
const ARGV = ['--repo', REPO, '--monitor-id', MONITOR_ID, '--state-file', STATE_FILE];

function fixtureUrl(name) {
  return new URL(name, FIX_DIR);
}

function readFixture(name) {
  return JSON.parse(readFileSync(fixtureUrl(name), 'utf8'));
}

function writeFixture(name, value) {
  writeFileSync(fixtureUrl(name), `${JSON.stringify(value, null, 2)}\n`);
}

// Builds cli.mjs `run()` deps that: (a) pin `now` to a fixed timestamp, (b)
// serve a fixed observation for fetchPRs/fetchIssues, and (c) read/write an
// in-memory snapshot so nothing touches the real filesystem or the run
// registry. `existingSnapshot` seeds the prior tick's state.
function makeDeps(observation, at, existingSnapshot) {
  let stored = existingSnapshot ?? null;
  return {
    fetchPRs: () => observation.pr,
    fetchIssues: () => observation.issue,
    readSnapshot: () => stored,
    writeSnapshotAtomic: (_path, data) => {
      stored = data;
    },
    now: () => at,
    env: {},
    get stored() {
      return stored;
    },
  };
}

function assertDeepEqualOrUpdate(actual, expectedFixtureName, message) {
  if (UPDATE) {
    writeFixture(expectedFixtureName, actual);
    return;
  }
  const expected = readFixture(expectedFixtureName);
  assert.deepEqual(actual, expected, message);
}

function contractBreakMessage(what) {
  return (
    `${what} for the zero-new-flags path no longer matches the committed golden ` +
    `fixture. This means the no-flags CLI output changed shape or content -- a ` +
    `BREAKING CONTRACT CHANGE that requires an explicit schemaVersion decision, ` +
    `not a fixture regeneration. See the comment at the top of this file.`
  );
}

test('contract-baseline: run1 seeds a baseline with no deltas', () => {
  const observation = readFixture('run1-observation.json');
  const deps = makeDeps(observation, '2026-01-01T00:00:00Z');
  const result = run(ARGV, deps);
  assert.equal(result.code, 0);
  assert.equal(result.report.baseline, true);
  assert.deepEqual(result.report.deltas, []);
  // Sanity: report only carries fields from the frozen contract list.
  for (const key of Object.keys(result.report)) {
    assert.ok(REPORT_FIELDS.includes(key), `unexpected report field "${key}" not in REPORT_FIELDS`);
  }
  assertDeepEqualOrUpdate(
    result.report,
    'run1-expected-report.json',
    contractBreakMessage('run1 report'),
  );
  assertDeepEqualOrUpdate(
    deps.stored,
    'run1-expected-snapshot.json',
    contractBreakMessage('run1 snapshot'),
  );
});

test('contract-baseline: run2 reports real deltas against the prior snapshot', () => {
  const observation = readFixture('run2-observation.json');
  const priorSnapshot = readFixture('run1-expected-snapshot.json');
  const deps = makeDeps(observation, '2026-01-01T01:00:00Z', priorSnapshot);
  const result = run(ARGV, deps);
  assert.equal(result.code, 10);
  assert.equal(result.report.deltas.length, 2);
  for (const delta of result.report.deltas) {
    assert.match(delta.id, /^[0-9a-f]{64}$/, `delta id "${delta.id}" must be 64-char sha256 hex`);
  }
  assertDeepEqualOrUpdate(
    result.report,
    'run2-expected-report.json',
    contractBreakMessage('run2 report'),
  );
  assertDeepEqualOrUpdate(
    deps.stored,
    'run2-expected-snapshot.json',
    contractBreakMessage('run2 snapshot'),
  );
});

test('contract-baseline: run3 is a no-change tick with zero deltas', () => {
  const observation = readFixture('run3-observation.json');
  const priorSnapshot = readFixture('run2-expected-snapshot.json');
  const deps = makeDeps(observation, '2026-01-01T02:00:00Z', priorSnapshot);
  const result = run(ARGV, deps);
  assert.equal(result.code, 0);
  assert.deepEqual(result.report.deltas, []);
  assertDeepEqualOrUpdate(
    result.report,
    'run3-expected-report.json',
    contractBreakMessage('run3 report'),
  );
  assertDeepEqualOrUpdate(
    deps.stored,
    'run3-expected-snapshot.json',
    contractBreakMessage('run3 snapshot'),
  );
});
