import { test } from 'node:test';
import assert from 'node:assert/strict';
import {
  cpSync,
  existsSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  symlinkSync,
  writeFileSync,
} from 'node:fs';
import { spawnSync } from 'node:child_process';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { HELP_COMMAND_KEYS, getHelpSpec } from '../lib/help.mjs';

const reference = new URL('../skills/gh-delta/references/', import.meta.url);
const normalize = (text) => text.replace(/\s+/g, ' ').trim();

test('command flag pages preserve every usage, option, default and description', () => {
  const index = readFileSync(new URL('flags.md', reference), 'utf8');
  for (const command of HELP_COMMAND_KEYS) {
    const spec = getHelpSpec(command);
    const filename = command === 'gh-delta' ? 'detector' : command.slice(9).replaceAll(' ', '-');
    const link = `flags/${filename}.md`;
    assert.ok(index.includes(`](${link})`), `${command} is reachable from the index`);
    const rawPage = readFileSync(new URL(link, reference), 'utf8');
    const page = normalize(rawPage);
    assert.ok(page.includes(normalize(spec.usage)), `${command}: usage`);
    const toc = /<!-- toc -->([\s\S]*?)<!-- \/toc -->/.exec(rawPage)?.[1];
    if (spec.options.length >= 6) {
      assert.ok(toc, `${command}: contents for six or more sections`);
      assert.equal([...toc.matchAll(/^- /gm)].length, spec.options.length);
    } else {
      assert.equal(toc, undefined, `${command}: short page needs no contents`);
    }

    for (const option of spec.options) {
      const syntax = option.valueName ? `${option.name} <${option.valueName}>` : option.name;
      assert.ok(page.includes(`\`${syntax}\``), `${command}: ${syntax}`);
      assert.ok(page.includes(normalize(option.description)), `${command}: ${syntax} description`);
      assert.ok(
        page.includes(normalize(`Default: \`${option.default ?? ''}\``)),
        `${command}: ${syntax} default`,
      );
    }
  }
});

test('skill check rejects missing, edited and retired command pages without rewriting them', (t) => {
  const root = fileURLToPath(new URL('../', import.meta.url));
  const dir = mkdtempSync(join(tmpdir(), 'gh-delta-flags-'));
  t.after(() => rmSync(dir, { recursive: true, force: true }));
  for (const entry of ['package.json', 'lib', 'tools/skill', 'skills/gh-delta/references']) {
    cpSync(join(root, entry), join(dir, entry), { recursive: true });
  }
  symlinkSync(join(root, 'node_modules'), join(dir, 'node_modules'), 'dir');
  const run = (...args) =>
    spawnSync(process.execPath, ['tools/skill/generate-flags.mjs', ...args], {
      cwd: dir,
      encoding: 'utf8',
    });
  const page = join(dir, 'skills/gh-delta/references/flags/watch-add.md');
  rmSync(page);
  assert.equal(run('--check').status, 1);
  assert.equal(existsSync(page), false);
  assert.equal(run().status, 0);
  writeFileSync(page, 'Edited reference\n');
  assert.equal(run('--check').status, 1);
  assert.equal(readFileSync(page, 'utf8'), 'Edited reference\n');
  assert.equal(run().status, 0);
  const retired = join(dir, 'skills/gh-delta/references/flags/retired.md');
  writeFileSync(
    retired,
    '<!-- Generated by tools/skill/generate-flags.mjs; do not edit by hand. -->\n',
  );
  assert.equal(run('--check').status, 1);
  assert.equal(existsSync(retired), true);
  assert.equal(run().status, 0);
  assert.equal(existsSync(retired), false);
  assert.equal(run('--check').status, 0);
  // A completely missing directory is another drift, not a successful empty check.
  rmSync(join(dir, 'skills/gh-delta/references/flags'), { recursive: true });
  assert.equal(run('--check').status, 1);
  assert.equal(existsSync(page), false);
});
