// Generate command-scoped references from the same help metadata the CLI exposes.
import { mkdirSync, readFileSync, readdirSync, unlinkSync, writeFileSync } from 'node:fs';
import prettier from 'prettier';
import { HELP_COMMAND_KEYS, getHelpSpec } from '../../lib/help.mjs';

const reference = new URL('../../skills/gh-delta/references/', import.meta.url);
const directory = new URL('flags/', reference);
const check = process.argv.slice(2).includes('--check');
const notice = '<!-- Generated by tools/skill/generate-flags.mjs; do not edit by hand. -->';
const index = [
  '# gh-delta flags',
  '',
  notice,
  '',
  'Generated from `lib/help.mjs`. Run `npm run build:skill` after help changes.',
  'Read only the command you need; [operating patterns](patterns.md) explain when to use it.',
  '',
];
const outputs = new Map();
for (const command of HELP_COMMAND_KEYS) {
  const spec = getHelpSpec(command);
  const name = command === 'gh-delta' ? 'detector' : command.slice(9).replaceAll(' ', '-');
  const filename = `flags/${name}.md`;
  index.push(`## ${spec.command}`, '', `[Usage, flags and defaults](${filename})`, '');
  const page = [
    `# ${spec.command}`,
    '',
    notice,
    '',
    '[All commands](../flags.md) · [Skill](../../SKILL.md)',
    '',
    `\`${spec.usage}\``,
    '',
  ];
  const body = [];
  const links = [];
  for (const option of spec.options) {
    const syntax = option.valueName ? `${option.name} <${option.valueName}>` : option.name;
    const anchor = syntax
      .toLowerCase()
      .replace(/[^\p{L}\p{N}\p{M}_\- ]/gu, '')
      .replaceAll(' ', '-');
    links.push(`- [${option.name}](#${anchor})`);
    body.push(
      `## \`${syntax}\``,
      '',
      `Default: \`${option.default ?? ''}\``,
      '',
      option.description,
      '',
    );
  }
  const lines = [...page, ...body].join('\n').split('\n').length;
  if (spec.options.length >= 6 || (lines > 150 && spec.options.length >= 3)) {
    page.push('<!-- toc -->', '', '**Contents**', '', ...links, '', '<!-- /toc -->', '');
  }
  outputs.set(filename, [...page, ...body].join('\n'));
}
outputs.set('flags.md', index.join('\n'));

if (!check) mkdirSync(directory, { recursive: true });
for (const [filename, text] of outputs) {
  const url = new URL(filename, reference);
  const generated = await prettier.format(text, { filepath: url.pathname });
  if (check) {
    let existing;
    try {
      existing = readFileSync(url, 'utf8');
    } catch (error) {
      if (error.code !== 'ENOENT') throw error;
    }
    if (existing !== generated) {
      process.stderr.write(`${filename} is missing or out of date; run npm run build:skill\n`);
      process.exitCode = 1;
    }
  } else {
    writeFileSync(url, generated);
  }
}
// Retired commands must not leave stale generated instructions in an installed skill.
let files = [];
try {
  files = readdirSync(directory);
} catch (error) {
  if (error.code !== 'ENOENT') throw error;
}
for (const filename of files) {
  if (!filename.endsWith('.md') || outputs.has(`flags/${filename}`)) continue;
  if (check) {
    process.stderr.write(`flags/${filename} is obsolete; run npm run build:skill\n`);
    process.exitCode = 1;
  } else {
    unlinkSync(new URL(filename, directory));
  }
}
