// Generate the skill's flag reference from the same help metadata the CLI exposes.
import { readFileSync, writeFileSync } from 'node:fs';
import prettier from 'prettier';
import { HELP_COMMAND_KEYS, getHelpSpec } from '../../lib/help.mjs';

const OUTPUT = new URL('../../skills/gh-delta/references/flags.md', import.meta.url);
const check = process.argv.slice(2).includes('--check');

const cell = (value) =>
  String(value ?? '')
    .replaceAll('|', '\\|')
    .replaceAll('\n', ' ');
const syntax = (option) =>
  option.valueName ? `${option.name} <${option.valueName}>` : option.name;

const sections = [
  '# gh-delta flags',
  '',
  '<!-- Generated by tools/skill/generate-flags.mjs; do not edit by hand. -->',
  '',
  'This reference is generated from `lib/help.mjs`. Run `npm run build:skill` after help changes.',
  '',
];

for (const command of HELP_COMMAND_KEYS) {
  const spec = getHelpSpec(command);
  sections.push(
    `## ${spec.command}`,
    '',
    `\`${spec.usage}\``,
    '',
    '| Flag | Default | Meaning |',
    '| --- | --- | --- |',
  );
  for (const option of spec.options) {
    sections.push(
      `| \`${cell(syntax(option))}\` | ${cell(option.default ?? '')} | ${cell(option.description)} |`,
    );
  }
  sections.push('');
}

const generated = await prettier.format(`${sections.join('\n')}\n`, {
  filepath: OUTPUT.pathname,
});
const existing = (() => {
  try {
    return readFileSync(OUTPUT, 'utf8');
  } catch (error) {
    if (error?.code === 'ENOENT') return null;
    throw error;
  }
})();

if (check) {
  if (existing !== generated) {
    process.stderr.write(
      'skills/gh-delta/references/flags.md is out of date; run npm run build:skill\n',
    );
    process.exitCode = 1;
  }
} else {
  writeFileSync(OUTPUT, generated);
}
